"""User added image_path

Revision ID: 4d1185157469
Revises: ba3b23956f0d
Create Date: 2024-10-28 12:38:26.585560

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4d1185157469"
down_revision: Union[str, None] = "ba3b23956f0d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("image_path", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "image_path")
    # ### end Alembic commands ###
