"""Updated datetime columns

Revision ID: 46a43e716816
Revises: 7b37da52e668
Create Date: 2024-12-22 12:17:24.515380

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "46a43e716816"
down_revision: Union[str, None] = "7b37da52e668"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "articles", "author_id", existing_type=sa.BIGINT(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "articles", "author_id", existing_type=sa.BIGINT(), nullable=True
    )
    # ### end Alembic commands ###
