"""Comment - renamed user_id -> author_id

Revision ID: afed8cee7bdf
Revises: 4d1185157469
Create Date: 2024-10-28 14:26:05.107262

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "afed8cee7bdf"
down_revision: Union[str, None] = "4d1185157469"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "comments", sa.Column("author_id", sa.Integer(), nullable=False)
    )
    op.drop_constraint("comments_user_id_fkey", "comments", type_="foreignkey")
    op.create_foreign_key(
        None, "comments", "users", ["author_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_column("comments", "user_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "comments",
        sa.Column(
            "user_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
    )
    op.drop_constraint(None, "comments", type_="foreignkey")
    op.create_foreign_key(
        "comments_user_id_fkey",
        "comments",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_column("comments", "author_id")
    # ### end Alembic commands ###
